### ISSUE TITLE
freefall sample : TimeoutException: Creating logger timed out

### ISSUE THREAD

**Issue by ValentinMerlet** [mbientlab/MetaWear-Tutorial-Android#1]
Hi !

First, very nice job for the MetaWear API, and thanks for the github and video examples.

I'm facing some issues trying to log the data using the Accelerometer module.

I retrieved the MainActivity from the freefall sample but I have the following error trying ro run : 

`Error setting up route
                                                            java.util.concurrent.TimeoutException: Creating logger timed out
                                                                at com.mbientlab.metawear.impl.LoggingImpl$1.run(LoggingImpl.java:223)
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                at java.lang.Thread.run(Thread.java:764)`

I don't know neither how to get the data from the Logging class. I didn't find anything about it in the documentation, how can I get the data inside `then()` callback  : 
```
logging.downloadAsync().continueWith(new Continuation<Void, Void>() {
                    @Override
                    public Void then(Task<Void> task) throws Exception {

                        if (task.isFaulted()) {
                            Log.i("freefall", "Log download failed");
                        } else {
                            // Log completed, but where are the data ? Inside task.getResult(), i'm just getting null 
                            Log.i(LOG_TAG, "Log download complete");
                        }

                        return null;
                    }
                });
```

**Comment by scaryghost** [comment]
Your board most likely has run out of loggers to allocate.  Either reset the board or call the `tearDown` fuction.
https://mbientlab.com/androiddocs/latest/metawearboard.html#tear-down

Handling logged data works in the same manner as streaming data, the only difference being the use of the Logging module.
https://mbientlab.com/androiddocs/latest/data_route.html#handling-data

**Comment by ValentinMerlet** [comment]
Thanks for the reply.

I'm already calling `tearDown` inside the `onServiceConnected()` and I tried a reset but the exception still raised :/ Should I try a hard reset ?

You said that is the same manner as streaming data to get the data inside `downloadAsync()` but I really don't know how to get the data from task object. 

Sorry for being a newbie and thanks again for the assistance 😣

**Comment by scaryghost** [comment]
You'll have to show me the code you are currently working with.

Yes, logging and streaming work very similar fashions.  Have you successfully streamed accelerometer data to your Android device?  If not, forget about logging for the moment and follow this tutorial:
https://mbientlab.com/tutorials/JavaAPIs.html#template-app

**Comment by ValentinMerlet** [comment]
Yes I copied the MainActivity from the freefall example without any change.s 

When `downLoadAsync()` is called, the "Log download complete" log is actually logged but I don't know where the data are. Is there a file which is created and uploaded to the Android device ? I don't know actually what is done under the hood when `downloadAsync()` is called.

I have successfully streamed the accelerometer data to my Android device creating a file with FileOutputStream java object, but I don't think this is the right way to do.

**Comment by scaryghost** [comment]
Ok, since you have working code of an accelerometer stream, replace `stream` with `log` then start the logger.  When you are ready to retrieve the data, stop the logger, call `downloadAsync`, then call `tearDown` if you are done using the board.  All the code you were already using to post process the data while streaming stays the same.

Again, show me the code you are currently working with.
