### ISSUE TITLE
(HELP) Cannot Resolve symbol ´seviceBinder´ and stream euler angles

### ISSUE THREAD

**Issue by echiul** [mbientlab/MetaWear-Tutorial-Android#3]
Hi, When I was programming following the YouTube video, I had a problem I appeared: Cannot Resolve symbol ´seviceBinder´ and I do not know how to continue, in addition to the above I wanted to know if the same can be done but instead of accelerating with euler angles.
Please help me that I am stuck with this. Thank you very much in advance

**Comment by scaryghost** [comment]
> Hi, When I was programming following the YouTube video, I had a problem I appeared: Cannot Resolve symbol ´seviceBinder´ and I do not know how to continue, 
The complete code for the tutorial is in this repo.  Compare what you have with what is in the tutorial project.

https://github.com/mbientlab/MetaWear-Tutorial-Android/tree/master/freefall

> in addition to the above I wanted to know if the same can be done but instead of accelerating with euler angles.

Yes, this is covered in the developer documentation: https://mbientlab.com/androiddocs/latest/
